import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div className="flex flex-col h-full">
          <nav className="bg-gray-800 p-4 text-white">
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="hover:text-gray-300">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/workout" className="hover:text-gray-300">
                  Workout Generator
                </Link>
              </li>
              <li>
                <Link href="/progress" className="hover:text-gray-300">Progress Tracking</Link>
              </li>
              <li>
                <Link href="/settings" className="hover:text-gray-300">Settings</Link>
              </li>
            </ul>
          </nav>
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
